name: Deploy

on:
  release:
    types: [created]

concurrency:
  group: production
  cancel-in-progress: false

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: install
        run: cd functions && npm install

      - name: Make .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          directory: functions
          envkey_ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          envkey_LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          envkey_LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
          envkey_LINE_PUSH_USER_ID: ${{ secrets.LINE_PUSH_USER_ID }}

      - name: Deploy Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --project ${{ vars.FIREBASE_PROJECT_ID }}
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
