name: lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          directory: functions
          envkey_ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          envkey_LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          envkey_LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
          envkey_LINE_PUSH_USER_ID: ${{ secrets.LINE_PUSH_USER_ID }}

      - name: install & lint
        run: cd functions && npm install && npm run lint:fix
