name: lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: functions
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
          cache-dependency-path: functions/package-lock.json

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          directory: functions
          envkey_ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          envkey_LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          envkey_LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
          envkey_LINE_PUSH_USER_ID: ${{ secrets.LINE_PUSH_USER_ID }}

      - name: install
        run: npm ci
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
